# Generated by Django 4.0.4 on 2022-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0002_rename_shortener_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.CharField(max_length=100),
        ),
    ]
